### ISSUE TITLE
建议优化

### ISSUE THREAD

**Issue by scriptiot-dev** [yoonper/doc#1]
代码很精简，简单高效，点个赞；如果下面三个点能够优化，那就很牛逼了：

+  左侧导航目录，每个子页面没有对应的url, 可以根据key生成独立的url，这样方便分享
+ 右侧导航目录层级现在只有一级，可以参考语雀进行多级目录优化
+ markdown主题可以选择比较好的主题，譬如参考 [马克飞象](https://maxiang.io/)

这是我们官方帮助手册，已经用上了，[https://scriptiot.github.io/evm_doc/](https://scriptiot.github.io/evm_doc/ 
)

感谢！！！

**Comment by yoonper** [comment]
1、2 两点在开发过程中我也有想到，有空我优化一下~
第 3 点可能每个人的审美不太一样，我不太喜欢马克飞象的样式，不过这次因为自己需求比较简单，所以把代码高亮给省了

**Comment by yoonper** [comment]
已优化 :P
